"""Generate build/generated/tinyfpga/*.v from the vendored TinyFPGA bootloader USB core (Apache-2.0).

The vendor files are not edited. The copies differ only where the slang front end of Yosys
refuses the original Verilog-2001 style:
  * strobe.v: the two parameters move into the module header (they are declared after the ports);
  * initial blocks: non-blocking `<=` becomes blocking `=` (usb_fs_in_pe, usb_fs_out_pe,
    usb_fs_tx, usb_serial_ctrl_ep initialise registers and the descriptor ROM that way).
Every copy carries the source path and sha256 in its first line.
"""
from pathlib import Path
import hashlib
import re

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'fpga/vendor/tinyfpga-bootloader/common'
OUT = ROOT / 'build/generated/tinyfpga'
FILES = ['usb_fs_pe.v', 'usb_fs_in_pe.v', 'usb_fs_out_pe.v', 'usb_fs_in_arb.v', 'usb_fs_out_arb.v', 'usb_fs_rx.v', 'usb_fs_tx.v',
         'usb_fs_tx_mux.v', 'usb_reset_det.v', 'usb_serial_ctrl_ep.v', 'usb_spi_bridge_ep.v', 'edge_detect.v', 'strobe.v']


def fix_initial_blocks(text):
    out, depth = [], 0
    for line in text.split('\n'):
        if depth == 0 and re.match(r'\s*initial\s+begin\b', line):
            depth = 1
            out.append(line)
            continue
        if depth:
            depth += len(re.findall(r'\bbegin\b', line)) - len(re.findall(r'\bend\b', line))
            line = line.replace('<=', '=')
            if depth <= 0:
                depth = 0
        out.append(line)
    return '\n'.join(out)


def generate():
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for name in FILES:
        src = SRC / name
        text = src.read_text(encoding='utf-8')
        if name == 'strobe.v':
            old_hdr = 'module strobe(\n'
            old_params = '\tparameter WIDTH = 1;\n\tparameter DELAY = 2; // 2 for metastability, larger for testing\n'
            assert text.count(old_hdr) == 1 and text.count(old_params) == 1, 'vendor strobe.v changed'
            text = text.replace(old_hdr, 'module strobe #(\n\tparameter WIDTH = 1,\n\tparameter DELAY = 2 // 2 for metastability, larger for testing\n) (\n')
            text = text.replace(old_params, '')
        text = fix_initial_blocks(text)
        dst = OUT / name
        dst.write_text(f'// GENERATED by fpga/tools/prepare_usb_core.py from {src.relative_to(ROOT).as_posix()} '
                       f'(sha256 {hashlib.sha256(src.read_bytes()).hexdigest()}); see the tool for the two changes.\n' + text,
                       encoding='utf-8', newline='\n')
        written.append(dst)
    return written


if __name__ == '__main__':
    print('wrote', len(generate()), 'files to', OUT)
