"""Generate build/generated/summercart64/memory_flash_dq.sv from the vendored SummerCart64
memory_flash.sv: the same controller (flash_qspi + memory_flash) with its data pins split into
out/oe/in ports so the board can share the flash between the boot-ROM reader and the USB
programmer with one tri-state driver per pad (fpga/rtl/sn64_bootrom_flash.sv). The vendor file
is not edited; the copy keeps its licence header (CERN-OHL-S-2.0, SummerCart64) and renames the
two modules (flash_qspi_dq, memory_flash_dq) so both versions can coexist in one build.

  python fpga/tools/prepare_flash_pads.py
"""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'fpga/vendor/summercart64/fw/rtl/memory/memory_flash.sv'
OUT = ROOT / 'build/generated/summercart64/memory_flash_dq.sv'
SPLIT_PORTS = ('    output logic [3:0] flash_dq_out_o,\n    output logic flash_dq_oe_s_o,\n'
               '    output logic flash_dq_oe_q_o,\n    input [3:0] flash_dq_i\n')
SUBS = [
    ('module flash_qspi (', 'module flash_qspi_dq ('),
    ('    inout [3:0] flash_dq\n', SPLIT_PORTS),                      # flash_qspi ports
    ("    assign flash_dq[0] = flash_dq_oe_s ? flash_dq_out[0] : 1'bZ;\n    assign flash_dq[3:1] = flash_dq_oe_q ? flash_dq_out[3:1] : 3'bZZZ;\n",
     '    assign flash_dq_out_o = flash_dq_out;\n    assign flash_dq_oe_s_o = flash_dq_oe_s;\n    assign flash_dq_oe_q_o = flash_dq_oe_q;\n'),
    ('        ff_dq_in <= flash_dq;\n', '        ff_dq_in <= flash_dq_i;\n'),
    ('module memory_flash (', 'module memory_flash_dq ('),
    ('    inout [3:0] flash_dq\n', SPLIT_PORTS),                      # memory_flash ports
    ('    flash_qspi flash_qspi_inst (', '    flash_qspi_dq flash_qspi_inst ('),
    ('        .flash_dq(flash_dq)', '        .flash_dq_out_o(flash_dq_out_o), .flash_dq_oe_s_o(flash_dq_oe_s_o), '
                                    '.flash_dq_oe_q_o(flash_dq_oe_q_o), .flash_dq_i(flash_dq_i)'),
]


def generate():
    text = SRC.read_text(encoding='utf-8')
    pos = 0
    for old, new in SUBS:                      # each anchor is the next occurrence after the previous one
        i = text.find(old, pos)
        assert i >= 0, f'vendor memory_flash.sv changed; anchor not found: {old[:50]!r}'
        text = text[:i] + new + text[i + len(old):]
        pos = i + len(new)
    header = (f'// GENERATED by fpga/tools/prepare_flash_pads.py from {SRC.relative_to(ROOT).as_posix()}\n'
              f'// (sha256 {hashlib.sha256(SRC.read_bytes()).hexdigest()}). Data pins split into out/oe/in ports,\n'
              f'// modules renamed flash_qspi_dq / memory_flash_dq; nothing else changed.\n')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + text, encoding='utf-8', newline='\n')
    return OUT


if __name__ == '__main__':
    print('wrote', generate())
