// SN64 v2 board top level (hardware/sn64-v2, LFE5U-85F CABGA381).
// One 27 MHz oscillator; every clock comes from the FPGA PLLs:
//   EHXPLLL with feedback from CLKOS: f_CLKOS = f_in / CLKI_DIV x CLKFB_DIV, f_VCO = f_CLKOS x CLKOS_DIV,
//   every output = f_VCO / its divider (PFD 3.125-400 MHz, VCO 400-800 MHz).
//   * pll_ntsc: 27/2 x 5 = 67.5 (CLKOS), VCO 472.5, CLKOP /22 = 21.477273 MHz (exact)
//   * pll_pal:  27/7 x 4 = 15.43 (CLKOS), VCO 617.14, CLKOP /29 = 21.280788 MHz (-27 ppm vs 21.28137)
//   * pll_host: 27 x 4 = 108 (CLKOS), VCO 432: CLKOP /9 = 48 MHz USB, CLKOS2 /36 = 12 MHz USB logic,
//               CLKOS3 /7 = 61.714 MHz host
// The SNES master is selected per region through a DCS and gated until the
// region is decided (sn64_top). Absorbed into the FPGA in v2: USB device
// (sn64_usb_prog), rail telemetry front end (sn64_rail_monitor over I2C to the
// TLA2528), cartridge audio ADC (sn64_sd_adc), open-drain pulls through the
// SN74LVC07A. Pin names follow hardware/sn64-v2/interfaces/fpga-pin-map.csv;
// constraints fpga/constraints/sn64_board.lpf (generated by pin_plan.py).
// SPDX-License-Identifier: GPL-3.0-or-later
module sn64_board_top (
    input  wire        osc_27,
    input  wire        board_reset_n,     // TPS3808 on FPGA_3V3
    // N64 bus (riser)
    input  wire        n64_reset_n, n64_nmi_n, n64_alel, n64_aleh, n64_read_n, n64_write_n,
    inout  wire [15:0] n64_ad,
    input  wire        n64_cic_clk, n64_si_clk,
    inout  wire        n64_cic_dq,
    inout  wire        n64_si_dq, n64_int_n,            // reserved, released
    // USB device
    inout  wire        usb_dp, usb_dn,
    output wire        usb_pu,                          // 1.5 k pull-up on D+
    // telemetry ADC (I2C, open drain)
    inout  wire        adc_scl, adc_sda,
    input  wire        efuse_fault_n, mux_status,
    output wire        cart_5v_enable,
    output wire        programn_od,                     // SN74LVC07A input: 0 = pull PROGRAMN
    output wire        led_status,
    // cartridge translators (A side)
    output wire [23:0] cart_address,
    output wire [7:0]  cart_pa,
    output wire        cart_rd_n, cart_wr_n, cart_prd_n, cart_pwr_n,
    output wire        cart_romsel_n, cart_wramsel_n, cart_refresh, cart_phi2, cart_sysclk,
    inout  wire [7:0]  cart_data,                       // U204 byte 1; driven only while data_dir = 1
    output wire        snes_cic_clk, snes_cic_slave_reset,
    input  wire        cic_data0_in, cic_data1_in, cart_irq_n, cart_reset_n_sense, expand_sense,
    output wire        cic_data0_od, cic_data1_od, reset_pull_od,   // SN74LVC07A inputs: 0 = pull the 5 V line low
    output wire        ctl_oe_n, cic_oe_n, data_oe_n, data_dir,
    // cartridge audio sigma-delta front end
    input  wire        aud_l_cmp, aud_r_cmp,            // LVDS comparators
    output wire        aud_l_fb, aud_r_fb,
    // configuration flash (MCLK via USRMCLK)
    output wire        flash_cs_n,
    inout  wire [3:0]  flash_dq
);
    // ---------------- PLLs ----------------
    wire clk_ntsc, clk_pal, clk_usb48, clk_host, clk_usb12;
    wire lock_ntsc, lock_pal, lock_host;
    wire fb_ntsc, fb_pal, fb_host;
    (* FREQUENCY_PIN_CLKI="27", FREQUENCY_PIN_CLKOP="21.477273", FREQUENCY_PIN_CLKOS="67.5", ICP_CURRENT="12", LPF_RESISTOR="8", MFG_ENABLE_FILTEROPAMP="1", MFG_GMCREF_SEL="2" *)
    EHXPLLL #(
        .PLLRST_ENA("DISABLED"), .INTFB_WAKE("DISABLED"), .STDBY_ENABLE("DISABLED"), .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"), .OUTDIVIDER_MUXB("DIVB"), .OUTDIVIDER_MUXC("DIVC"), .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(2), .CLKOP_ENABLE("ENABLED"), .CLKOP_DIV(22), .CLKOP_CPHASE(10), .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"), .CLKOS_DIV(7), .CLKOS_CPHASE(2), .CLKOS_FPHASE(0),
        .FEEDBK_PATH("CLKOS"), .CLKFB_DIV(5)
    ) pll_ntsc (
        .RST(1'b0), .STDBY(1'b0), .CLKI(osc_27), .CLKOP(clk_ntsc), .CLKOS(fb_ntsc), .CLKFB(fb_ntsc), .CLKINTFB(),
        .PHASESEL0(1'b0), .PHASESEL1(1'b0), .PHASEDIR(1'b1), .PHASESTEP(1'b1), .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0), .ENCLKOP(1'b0), .LOCK(lock_ntsc));
    (* FREQUENCY_PIN_CLKI="27", FREQUENCY_PIN_CLKOP="21.280788", FREQUENCY_PIN_CLKOS="15.428571", ICP_CURRENT="12", LPF_RESISTOR="8", MFG_ENABLE_FILTEROPAMP="1", MFG_GMCREF_SEL="2" *)
    EHXPLLL #(
        .PLLRST_ENA("DISABLED"), .INTFB_WAKE("DISABLED"), .STDBY_ENABLE("DISABLED"), .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"), .OUTDIVIDER_MUXB("DIVB"), .OUTDIVIDER_MUXC("DIVC"), .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(7), .CLKOP_ENABLE("ENABLED"), .CLKOP_DIV(29), .CLKOP_CPHASE(14), .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"), .CLKOS_DIV(40), .CLKOS_CPHASE(19), .CLKOS_FPHASE(0),
        .FEEDBK_PATH("CLKOS"), .CLKFB_DIV(4)
    ) pll_pal (
        .RST(1'b0), .STDBY(1'b0), .CLKI(osc_27), .CLKOP(clk_pal), .CLKOS(fb_pal), .CLKFB(fb_pal), .CLKINTFB(),
        .PHASESEL0(1'b0), .PHASESEL1(1'b0), .PHASEDIR(1'b1), .PHASESTEP(1'b1), .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0), .ENCLKOP(1'b0), .LOCK(lock_pal));
    (* FREQUENCY_PIN_CLKI="27", FREQUENCY_PIN_CLKOP="48", FREQUENCY_PIN_CLKOS="108", FREQUENCY_PIN_CLKOS2="12", FREQUENCY_PIN_CLKOS3="61.714286", ICP_CURRENT="12", LPF_RESISTOR="8", MFG_ENABLE_FILTEROPAMP="1", MFG_GMCREF_SEL="2" *)
    EHXPLLL #(
        .PLLRST_ENA("DISABLED"), .INTFB_WAKE("DISABLED"), .STDBY_ENABLE("DISABLED"), .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"), .OUTDIVIDER_MUXB("DIVB"), .OUTDIVIDER_MUXC("DIVC"), .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(1), .CLKOP_ENABLE("ENABLED"), .CLKOP_DIV(9), .CLKOP_CPHASE(3), .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"), .CLKOS_DIV(4), .CLKOS_CPHASE(1), .CLKOS_FPHASE(0),
        .CLKOS2_ENABLE("ENABLED"), .CLKOS2_DIV(36), .CLKOS2_CPHASE(17), .CLKOS2_FPHASE(0),
        .CLKOS3_ENABLE("ENABLED"), .CLKOS3_DIV(7), .CLKOS3_CPHASE(2), .CLKOS3_FPHASE(0),
        .FEEDBK_PATH("CLKOS"), .CLKFB_DIV(4)
    ) pll_host (
        .RST(1'b0), .STDBY(1'b0), .CLKI(osc_27), .CLKOP(clk_usb48), .CLKOS(fb_host), .CLKOS2(clk_usb12), .CLKOS3(clk_host),
        .CLKFB(fb_host), .CLKINTFB(),
        .PHASESEL0(1'b0), .PHASESEL1(1'b0), .PHASEDIR(1'b1), .PHASESTEP(1'b1), .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0), .ENCLKOP(1'b0), .ENCLKOS(1'b0), .ENCLKOS2(1'b0), .ENCLKOS3(1'b0), .LOCK(lock_host));
    wire pll_locked = lock_ntsc & lock_pal & lock_host;

    // ---------------- SNES master: region select, then run gate ----------------
    wire snes_clk_run, region_pal, clk_snes;
    reg  sel_ntsc = 1'b0, sel_pal = 1'b0;
    always @(posedge osc_27) begin
        sel_ntsc <= snes_clk_run & !region_pal;
        sel_pal  <= snes_clk_run &  region_pal;
    end
    DCSC #(.DCSMODE("NEG")) snes_clock (.CLK0(clk_ntsc), .CLK1(clk_pal), .SEL0(sel_ntsc), .SEL1(sel_pal),
                                        .MODESEL(1'b0), .DCSOUT(clk_snes));

    // Power-on reset: board supervisor and PLL lock.
    wire por_n = board_reset_n & pll_locked;

    // ---------------- Rail / temperature monitor (I2C ADC) ----------------
    wire scl_oe, sda_oe;
    wire host_3v3_ok, sys_5v_ok, cart_5v_ok, core_1v1_ok, overtemp, monitor_error;
    wire [127:0] adc_codes;
    // Cartridge check: the monitor feeds a small test current into the switched-off cartridge
    // rail through the ADC's channel 3 and reports the rail voltage to the sequencer in sn64_top.
    wire cart_probe_req, cart_probe_active, cart_probe_strobe; wire [11:0] cart_probe_code;
    sn64_rail_monitor #(.CLK_HZ(27_000_000)) monitor (
        .clk(osc_27), .rst_n(board_reset_n), .scl_oe(scl_oe), .sda_oe(sda_oe), .sda_in(adc_sda),
        .host_3v3_ok(host_3v3_ok), .sys_5v_ok(sys_5v_ok), .cart_5v_ok(cart_5v_ok), .core_1v1_ok(core_1v1_ok),
        .overtemp(overtemp), .error(monitor_error), .codes(adc_codes),
        .probe_req(cart_probe_req), .probe_active(cart_probe_active), .probe_strobe(cart_probe_strobe),
        .probe_code(cart_probe_code));
    assign adc_scl = scl_oe ? 1'b0 : 1'bz;
    assign adc_sda = sda_oe ? 1'b0 : 1'bz;
    wire fpga_rails_ok = core_1v1_ok & sys_5v_ok & board_reset_n;

    // ---------------- USB programmer ----------------
    wire usb_p_tx, usb_n_tx, usb_tx_en, usb_boot, usb_host;
    wire spi_cs_n_u, spi_sck_u, spi_mosi_u, spi_miso_u, spi_active;
    reg  usb_rst = 1'b1;
    always @(posedge clk_usb12) usb_rst <= !pll_locked;
    sn64_usb_prog usb (
        .clk_48mhz(clk_usb48), .clk(clk_usb12), .reset(usb_rst),
        .usb_p_tx(usb_p_tx), .usb_n_tx(usb_n_tx), .usb_p_rx(usb_tx_en ? 1'b1 : usb_dp), .usb_n_rx(usb_tx_en ? 1'b0 : usb_dn),
        .usb_tx_en(usb_tx_en),
        .spi_cs_n(spi_cs_n_u), .spi_sck(spi_sck_u), .spi_mosi(spi_mosi_u), .spi_miso(spi_miso_u),
        .boot_request(usb_boot), .sof_seen(usb_host));
    assign usb_dp = usb_tx_en ? usb_p_tx : 1'bz;
    assign usb_dn = usb_tx_en ? usb_n_tx : 1'bz;
    assign usb_pu = pll_locked;                           // attach once the clocks run
    // Reboot on the host's command: hold PROGRAMN low for ~1 ms through the open-drain driver.
    reg [14:0] prog_timer = '0;
    always @(posedge clk_usb12) begin
        if (usb_boot) prog_timer <= 15'd12000;
        else if (prog_timer != 0) prog_timer <= prog_timer - 1'b1;
    end
    assign programn_od = (prog_timer == 0);

    // ---------------- Cartridge pads ----------------
    wire [7:0] cart_data_out, cart_data_in;
    assign cart_data = data_dir ? cart_data_out : 8'bz;   // FPGA drives only when U204 points A->B
    assign cart_data_in = cart_data;
    wire cart_reset_pull;                                 // sn64_top: 1 = hold socket /RESET
    assign reset_pull_od = !cart_reset_pull;
    wire d0_o, d0_oe, d1_o, d1_oe;
    assign cic_data0_od = !(d0_oe & !d0_o);               // open drain: pull only to drive a 0
    assign cic_data1_od = !(d1_oe & !d1_o);
    assign n64_si_dq = 1'bz;                              // no SI/EEPROM function yet
    assign n64_int_n = 1'bz;                              // no cartridge interrupt yet

    wire [15:0] status_word;
    sn64_top #(.ROM_ADDR_BITS(17), .ROM_FROM_FLASH(1), .FLASH_USE_USRMCLK(1), .CLK25_HZ(27_000_000),      // 256 KiB flash ROM window
               .SEQ_PROBE_ENABLE(1)) top (                                                                    // cartridge check before 5 V
        .clk_25(osc_27), .clk_host(clk_host), .clk_snes(clk_snes), .por_n(por_n),
        .n64_reset_n(n64_reset_n), .n64_nmi_n(n64_nmi_n), .n64_alel(n64_alel), .n64_aleh(n64_aleh),
        .n64_read_n(n64_read_n), .n64_write_n(n64_write_n), .n64_ad(n64_ad),
        .n64_cic_clk(n64_cic_clk), .n64_si_clk(n64_si_clk), .n64_cic_dq(n64_cic_dq),
        .rom_we(1'b0), .rom_waddr('0), .rom_wdata(16'd0),
        .flash_sck(), .flash_cs_n(flash_cs_n), .flash_dq(flash_dq),
        .ext_spi_sel_req(!spi_cs_n_u), .ext_spi_sck(spi_sck_u), .ext_spi_cs_n(spi_cs_n_u), .ext_spi_mosi(spi_mosi_u),
        .ext_spi_miso(spi_miso_u), .ext_spi_active(spi_active),
        .pll_locked(pll_locked), .monitor_error(monitor_error),
        .snes_clk_run(snes_clk_run), .region_pal(region_pal),
        .host_3v3_ok(host_3v3_ok), .fpga_rails_ok(fpga_rails_ok), .cart_5v_ok(cart_5v_ok), .iface_rail_ok(1'b1),
        .efuse_fault_n(efuse_fault_n), .overtemp(overtemp), .cart_5v_enable(cart_5v_enable), .iface_rail_enable(),
        .cart_probe_req(cart_probe_req), .cart_probe_active(cart_probe_active), .cart_probe_strobe(cart_probe_strobe),
        .cart_probe_code(cart_probe_code),
        .cart_address(cart_address), .cart_pa(cart_pa), .cart_rd_n(cart_rd_n), .cart_wr_n(cart_wr_n),
        .cart_prd_n(cart_prd_n), .cart_pwr_n(cart_pwr_n), .cart_romsel_n(cart_romsel_n), .cart_wramsel_n(cart_wramsel_n),
        .cart_refresh(cart_refresh), .cart_phi2(cart_phi2), .cart_sysclk(cart_sysclk),
        .cart_data_out(cart_data_out), .cart_data_in(cart_data_in), .cart_irq_n(cart_irq_n), .cart_reset_n_sense(cart_reset_n_sense),
        .cart_reset_pull(cart_reset_pull), .ctl_oe_n(ctl_oe_n), .data_oe_n(data_oe_n), .data_dir(data_dir),
        .snes_cic_oe_n(cic_oe_n), .snes_cic_clk(snes_cic_clk), .snes_cic_slave_reset(snes_cic_slave_reset),
        .snes_cic_data0_o(d0_o), .snes_cic_data0_oe(d0_oe), .snes_cic_data0_i(cic_data0_in),
        .snes_cic_data1_o(d1_o), .snes_cic_data1_oe(d1_oe), .snes_cic_data1_i(cic_data1_in),
        .aud_l_cmp(aud_l_cmp), .aud_r_cmp(aud_r_cmp), .aud_l_fb(aud_l_fb), .aud_r_fb(aud_r_fb),
        .status_word(status_word));

    // Status LED: steady while the SNES clock runs, blinking while a USB host talks to us.
    reg [23:0] blink = '0;
    always @(posedge osc_27) blink <= blink + 1'b1;
    assign led_status = usb_host ? blink[23] : status_word[12];
    wire unused = &{1'b0, expand_sense, mux_status, spi_active, adc_codes};
endmodule
