"""Turn the two splash logos into the picture data the boot menu draws at start-up.

Order on the screen (owner, 2026-10-01): the SN64 logo, then the FantomZap logo, then the menu.
Sources, both in this repository:
  assets/logo/sn64-logo-on-dark.svg                    the SN64 logo for dark backgrounds (make_logo.py)
  assets/logo/fantomzap/fantomzap-wordmark-mono.svg    the owner's logo, outlines traced from his artwork

Each logo is drawn at its screen size (the menu screen is 320 x 240), put on black, and reduced to a
palette. The result is src/sn64_splash_data.c: for each picture a palette (RGB) and one byte per
pixel. Colour 0 is always the black background. The ROM stores its program compressed, so the flat
areas cost little.

  python tools/make_splash.py            (needs PyMuPDF and Pillow)
"""
import argparse
import hashlib
import zlib
from pathlib import Path

import pymupdf
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OVERSAMPLE = 4

# name, source, width of the artwork on the screen, colours
PICTURES = [
    ('sn64', 'assets/logo/sn64-logo-on-dark.svg', 272, 64),
    ('fantomzap', 'assets/logo/fantomzap/fantomzap-wordmark-mono.svg', 280, 16),
]


def render(svg, width):
    """The artwork of the SVG (its page without the empty margins) `width` pixels wide as RGBA,
    drawn larger first and reduced for smooth edges."""
    page = pymupdf.open(svg)[0]

    def draw(zoom):
        pix = page.get_pixmap(matrix=pymupdf.Matrix(zoom, zoom), alpha=True)
        return Image.frombytes('RGBA', (pix.width, pix.height), pix.samples)
    probe = draw(600 / page.rect.width)
    x0, y0, x1, y1 = probe.getchannel('A').getbbox()
    share = (x1 - x0) / probe.width                         # how much of the page width the artwork takes
    big = draw(width * OVERSAMPLE / (page.rect.width * share))
    big = big.crop(big.getchannel('A').getbbox())
    return big.resize((width, round(width * big.height / big.width)), Image.LANCZOS)


def on_black(rgba, white):
    """Composite on black. `white`: the artwork is a one-colour shape, shown white."""
    if white:
        a = rgba.getchannel('A')
        return Image.merge('RGB', (a, a, a))
    out = Image.new('RGBA', rgba.size, (0, 0, 0, 255))
    out.alpha_composite(rgba)
    return out.convert('RGB')


def to_palette(rgb, colours, grey):
    """(palette as a list of (r, g, b), pixels as bytes); entry 0 is black."""
    if grey:                                              # even grey steps: black, ..., white
        levels = colours - 1
        pal = [(round(i * 255 / levels),) * 3 for i in range(colours)]
        px = bytes(min(levels, (v * levels + 127) // 255) for v in rgb.getchannel('R').tobytes())
        return pal, px
    # maximum coverage keeps the small coloured areas (median cut merged the blue and the green button)
    q = rgb.quantize(colors=colours, method=Image.Quantize.MAXCOVERAGE, kmeans=4, dither=Image.Dither.NONE)
    raw = q.getpalette()[:colours * 3]
    pal = [tuple(raw[i:i + 3]) for i in range(0, len(raw), 3)]
    data = q.tobytes()
    used = sorted(set(data))
    darkest = min(used, key=lambda i: sum(pal[i]))
    order = [darkest] + [i for i in used if i != darkest]
    remap = {old: new for new, old in enumerate(order)}
    pal = [pal[i] for i in order]
    pal[0] = (0, 0, 0)
    return pal, bytes(remap[v] for v in data)


def c_bytes(data, per_line=32):
    lines = []
    for i in range(0, len(data), per_line):
        lines.append('    ' + ','.join(str(b) for b in data[i:i + per_line]) + ',')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out', type=Path, default=HERE.parent / 'src/sn64_splash_data.c')
    ap.add_argument('--preview', type=Path, default=None, help='also write the pictures as a PNG, one under the other')
    args = ap.parse_args()
    parts = ['// SPDX-License-Identifier: GPL-3.0-or-later',
             '// Splash pictures for the boot menu. GENERATED by tools/make_splash.py: do not edit.',
             '// The FantomZap name and logo belong to the owner and are not under the open licences (see NOTICE).',
             '#include "sn64_splash.h"', '']
    previews = []
    for name, rel, width, colours in PICTURES:
        src = ROOT / rel
        grey = name == 'fantomzap'
        rgb = on_black(render(src, width), white=grey)
        pal, px = to_palette(rgb, colours, grey)
        w, h = rgb.size
        assert len(px) == w * h and max(px) < len(pal) <= 256
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        parts += [f'// {rel} (SHA-256 {sha[:16]}...), {w} x {h}, {len(pal)} colours',
                  f'static const uint8_t {name}_palette[{len(pal)}][3] = {{',
                  '    ' + ', '.join('{%d,%d,%d}' % c for c in pal) + ',', '};',
                  f'static const uint8_t {name}_pixels[{w * h}] = {{', c_bytes(px), '};',
                  f'const sn64_splash_image_t sn64_splash_{name} = {{ {w}, {h}, {len(pal)}, {name}_palette, {name}_pixels }};', '']
        back = Image.new('RGB', (w, h))
        back.putdata([pal[v] for v in px])
        previews.append(back)
        print(f'{name}: {w} x {h}, {len(pal)} colours, {w * h} bytes, about {len(zlib.compress(px, 9))} compressed')
    args.out.write_text('\n'.join(parts), encoding='utf-8', newline='\n')
    print('wrote', args.out.name)
    if args.preview:
        sheet = Image.new('RGB', (320, 240 * len(previews)))
        for i, im in enumerate(previews):
            sheet.paste(im, ((320 - im.width) // 2, i * 240 + (240 - im.height) // 2))
        sheet.resize((sheet.width * 3, sheet.height * 3), Image.NEAREST).save(args.preview)
        print('wrote', args.preview.name)


if __name__ == '__main__':
    main()
