"""Generate the boot menu's credits roll from CREDITS.md.

The roll is the repository's credits file put on the console's screen: the credit line and
source location from NOTICE, the thank-you paragraph, every project and its people from the
tables of CREDITS.md in the order they stand there, the tools, and the last section (the SN64
crew) as "Role: Who" lines at the very end. Lines are wrapped to 36 columns: two short of the
menu's 38, so that nobody's name stands at the very edge of the screen, where a television may
cut it off.

  python tools/make_credits.py            writes src/sn64_credits_data.c
  python tools/make_credits.py --check    fails if that file is not what CREDITS.md gives now

So a row added to CREDITS.md appears in the roll after `make credits`, and `make test` catches a
roll that was not regenerated.
"""
import argparse
import re
import sys
import textwrap
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
COLUMNS = 36
CREDIT_LINE = 'SN64 by FantomZap'                 # NOTICE: the attribution every notice shown by the work keeps
CREW_SECTION = 'The SN64 crew'
BS = chr(92)
TEXT, TITLE, PROJECT, PEOPLE, CREW = range(5)      # sn64_credit_kind_t in src/sn64_credits.h


def plain(text):
    """Markdown to screen text: links to their text, no backticks, 7-bit only."""
    text = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', text)
    text = text.replace('`', '').replace('*', '')
    text = re.sub(r'\s+', ' ', text)
    return ''.join(ch for ch in text if 32 <= ord(ch) < 127).strip()


def wrap(text, first='', rest=''):
    return textwrap.wrap(text, width=COLUMNS, initial_indent=first, subsequent_indent=rest,
                         break_long_words=False, break_on_hyphens=False) or ['']


def source_location(notice):
    m = re.search(r'^Source location:\s*https?://(\S+)\s*$', notice, re.M)
    if not m:
        sys.exit('NOTICE has no "Source location:" line')
    return m.group(1)


def paragraphs(text):
    return [p for p in re.split(r'\n\s*\n', text) if p.strip()]


def roll(credits_md, notice):
    """The roll as [(line, kind), ...]."""
    out = []

    def add(kind, texts):
        out.extend((t, kind) for t in texts)

    add(TITLE, [CREDIT_LINE])
    add(PROJECT, [source_location(notice)])
    add(TEXT, [''])
    blocks = re.split(r'^## +', credits_md, flags=re.M)
    intro = blocks[0].partition('\n')[2] if blocks[0].startswith('# ') else blocks[0]
    for para in paragraphs(intro):
        add(TEXT, wrap(plain(para)) + [''])
    crew = None
    for block in blocks[1:]:
        title, _, body = block.partition('\n')
        title = title.strip()
        rows = [r for r in body.splitlines() if r.startswith('|')]
        cells = [[c.strip() for c in r.strip().strip('|').split('|')] for r in rows[2:]]   # skip header and rule
        if title == CREW_SECTION:
            crew = cells
            continue
        add(TEXT, [''])
        add(TITLE, wrap(plain(title).upper()))
        add(TEXT, [''])
        if cells:
            for c in cells:
                add(PROJECT, wrap(plain(c[0])))
                add(PEOPLE, wrap(plain(c[1]), '  ', '    '))
        else:
            add(PEOPLE, wrap(plain(paragraphs(body)[0])))      # a section of prose (the tools): its first paragraph
    if not crew:
        sys.exit('CREDITS.md has no "%s" table' % CREW_SECTION)
    add(TEXT, ['', ''])
    for role, who in crew:
        both = '%s: %s' % (plain(role), plain(who))
        # on one line if it fits; otherwise the role, then who on a line of their own
        add(CREW, [both] if len(both) <= COLUMNS else [plain(role) + ':'] + wrap(plain(who), '  ', '  '))
    for ln, _ in out:
        assert len(ln) <= COLUMNS and all(32 <= ord(ch) < 127 for ch in ln), ln
    return out


def c_source(lines):
    out = ['// SPDX-License-Identifier: GPL-3.0-or-later',
           '// The credits roll of the boot menu. GENERATED by tools/make_credits.py from CREDITS.md and',
           '// NOTICE (`make credits`); do not edit. Third-party names are credits, not endorsements: see',
           '// CREDITS.md.',
           '#include "sn64_credits.h"',
           '',
           'const char *const sn64_credits_lines[] = {']
    for ln, _ in lines:
        out.append('    "%s",' % ln.replace(BS, BS + BS).replace('"', BS + '"'))
    out += ['};', '', '// What each line is (sn64_credit_kind_t): the screen colours it by that.',
            'const unsigned char sn64_credits_kind[] = {']
    kinds = [str(k) for _, k in lines]
    for i in range(0, len(kinds), 25):
        out.append('    ' + ', '.join(kinds[i:i + 25]) + ',')
    out += ['};', '', 'const int sn64_credits_count = %d;' % len(lines), '']
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true', help='only compare the generated file with CREDITS.md')
    ap.add_argument('--out', type=Path, default=HERE.parent / 'src/sn64_credits_data.c')
    args = ap.parse_args()
    lines = roll((ROOT / 'CREDITS.md').read_text(encoding='utf-8'), (ROOT / 'NOTICE').read_text(encoding='utf-8'))
    text = c_source(lines)
    if args.check:
        have = args.out.read_text(encoding='utf-8').replace('\r\n', '\n') if args.out.exists() else ''
        if have != text:
            sys.exit('FAIL: %s is not what CREDITS.md gives now; run `make credits`' % args.out.name)
        print('PASS: credits roll matches CREDITS.md (%d lines, ends "%s")' % (len(lines), lines[-1][0].strip()))
        return
    args.out.write_text(text, encoding='utf-8', newline='\n')
    print('wrote %s: %d lines' % (args.out.name, len(lines)))


if __name__ == '__main__':
    main()
