// SPDX-License-Identifier: GPL-3.0-or-later
// The look of the boot menu (owner, 2026-10-01): the SN64 logo centred at the top as the
// title, the rows of the menu left-justified as one block that stands a little right of the
// screen's edge so that it looks centred, and colour themes (sn64_theme.h).
//
// The main menu and Settings are drawn here whole. The text screens (status, alerts, about,
// credits ...) take their background and their small title from here and write their lines
// themselves.
//
// Pure C, no libdragon dependency: drawn into a 16-bit frame buffer and unit-tested on the
// host (tests/test_menuview.c), which also writes the screens out for the mock-ups. Text is
// drawn by the caller.
#ifndef SN64_MENUVIEW_H
#define SN64_MENUVIEW_H

#include <stdbool.h>
#include <stdint.h>

#include "sn64_padview.h"
#include "sn64_theme.h"

// ---- the title: the SN64 logo with see-through edges (src/sn64_title_data.c, generated by
// tools/make_title.py). One byte a pixel: the three top bits say how solid it is (0: nothing,
// 7: all of it), the five low bits which colour (0: ink, the theme's colour for the ring and
// the letters; else an entry of the palette).
typedef struct {
    uint16_t        w, h;
    uint16_t        colours;        // entries of the palette; entry 0 stands for the ink
    const uint16_t *palette;        // the screen's own 16-bit colours
    const uint8_t  *pixels;         // w * h, row by row from the top
} sn64_title_image_t;

extern const sn64_title_image_t sn64_title_large;   // for the main menu and Settings
extern const sn64_title_image_t sn64_title_small;   // for the top of a text screen

// The logo at (x0, y0), laid over what is already there.
void sn64_menu_logo(const sn64_canvas_t *c, int x0, int y0, const sn64_title_image_t *img, uint16_t ink);

// ---- what every screen starts with
// The whole screen in the theme's background colour.
void sn64_menu_clear(const sn64_canvas_t *c, const sn64_theme_t *t);
// The title: the logo centred at the top with a rule in the logo's four colours (green, blue,
// yellow, red from the left). `large`: for the main menu and Settings, the rule under the logo.
// Else the small one for a text screen, the rule running out to both sides of the logo; it
// leaves the screen free from SN64_MENU_TEXT_TOP down.
void sn64_menu_title(const sn64_canvas_t *c, const sn64_theme_t *t, bool large);
#define SN64_TITLE_LARGE_Y        8     // the top of the large logo ...
#define SN64_TITLE_LARGE_RULE_Y   64    // ... and its rule, two rows high
#define SN64_TITLE_SMALL_Y        6
#define SN64_TITLE_SMALL_RULE_Y   15
#define SN64_TITLE_MARGIN         16    // the small title's rule starts and ends this far from the screen's edges
#define SN64_MENU_TEXT_TOP        32

// ---- the two menus
enum { SN64_MAIN_PLAY, SN64_MAIN_MAPPING, SN64_MAIN_SETTINGS, SN64_MAIN_POWER_OFF, SN64_MAIN_ITEMS };
enum { SN64_SET_COMPAT, SN64_SET_THEME, SN64_SET_STATUS, SN64_SET_CREDITS, SN64_SET_ABOUT, SN64_SET_ITEMS };

// Where the rows stand: one block, left-justified, on a panel that is centred on the screen
// (owner, 2026-10-01: left-justified, "not indented but just moved right a bit to look more
// centered").
#define SN64_MENU_X        58       // the left edge of the block: the rows' marks, the lines over and under the rows
#define SN64_MENU_TEXT_X   80       // the rows' text
#define SN64_MENU_PANEL_X0 44       // the panel behind the rows ...
#define SN64_MENU_PANEL_X1 275
#define SN64_MENU_BAR_X0   50       // ... and on it the bar behind the row under the cursor
#define SN64_MENU_BAR_X1   269
#define SN64_MENU_HEAD_Y   71       // the line over the rows
#define SN64_MENU_ROWS_Y   86
#define SN64_MENU_ROW_H    20
#define SN64_MENU_UNDER    6        // the line under the rows stands this far below the last row's end
#define SN64_MENU_COLUMNS  30       // characters that fit from SN64_MENU_X to the screen's right margin

typedef struct {
    int         cursor;             // the row the cursor is on
    const char *head;               // the line over the rows: the cartridge in a word, or the menu's name
    bool        head_bad;           // ... in the warning colour
    const char *message;            // the line under the rows: a note or a refusal; "" for none
    bool        message_bad;
    const char *warning[2];         // standing warnings under that; NULL for none
} sn64_menu_view_t;

// The main menu: Play, Controller mapping, Settings, Power off cartridge, each with a round
// mark in one of the logo's four colours.
void sn64_menu_draw_main(const sn64_canvas_t *c, sn64_text_fn text, void *ctx, const sn64_theme_t *t,
                         const sn64_menu_view_t *v);
// Settings: Compatibility mode, Theme, Status / diagnostics, Credits, About. `compat` and
// `theme_index` are what the first two rows say.
void sn64_menu_draw_settings(const sn64_canvas_t *c, sn64_text_fn text, void *ctx, const sn64_theme_t *t,
                             const sn64_menu_view_t *v, bool compat, unsigned theme_index);

// ---- About (Settings, About; owner, 2026-10-01: "move all the version stuff and odd info to an
// about section in settings"): who made it and where the source is, the versions, the licences.
// Only the text: the caller writes the lines one under the other below the small title, each in
// the colour its kind names.
#define SN64_ABOUT_LINES    15
#define SN64_ABOUT_COLUMNS  36
enum { SN64_LINE_TEXT, SN64_LINE_DIM, SN64_LINE_HI, SN64_LINE_WARN };
typedef struct {
    const char *credit, *source;    // the credit line and where the source is: the credits roll's first two lines
    const char *menu_version;       // of this program
    bool        present;            // the SN64's registers answered
    uint16_t    magic, version, features;
    unsigned    tv;                 // the console: 0 PAL, 1 NTSC, 2 M-PAL
} sn64_about_t;
void sn64_menu_about(const sn64_about_t *a, char text[SN64_ABOUT_LINES][SN64_ABOUT_COLUMNS + 1],
                     uint8_t kind[SN64_ABOUT_LINES]);

#endif
