// SPDX-License-Identifier: GPL-3.0-or-later
// The outline of a controller picture as pixel runs, one list per row of its picture box.
// The data (src/sn64_padshape_data.c) is generated by tools/make_padshapes.py.
#ifndef SN64_PADSHAPE_H
#define SN64_PADSHAPE_H

#include <stdint.h>

typedef struct {
    uint8_t        top;     // the first row of the picture box that has any
    uint8_t        rows;
    const uint8_t *runs;    // for each row: how many runs (1 to 3), then the first and last pixel of each
} sn64_padshape_t;

extern const sn64_padshape_t sn64_padshape_trident;     // three handles: the Nintendo 64 controller's shape
extern const sn64_padshape_t sn64_padshape_brawler;     // two long handles
extern const sn64_padshape_t sn64_padshape_eightbitdo;  // two short round handles

#endif
